### ISSUE TITLE
Maybe it is a bug for EEPROM  on TMC-UPS-10A/70V PowerStage board

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#10]
In issues #9, I tried hard to get the EEPROM work on the PowerStage board, but failed.

Finally, I found the problem is that we cannot connect the corresponding pins together, and we have to switch PIN28 and PIN29. That is the AT25128B's SI should be connected to MOSI(PIN29), not MISO(PIN28).

The EEPROM connection on the TMC4671-EVAL is correct!

**Comment by trinamic-LH** [comment]
Are you manually wiring everything together or are you using the Eselsbrücke Connector?

**Comment by trinamic-LH** [comment]
It appears that the TMC-UPS-10A/70V v1.1 aswell as the TMC-UPS-2A24V v1.1 have the SPI data lines flipped. This will be fixed in the next revision, which is already being worked on.

Thank you for the issue report
