### ISSUE TITLE
Problems for reading TMC6200's register (address 0x04)

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#11]
Hi, when I use the following code to read TMC6200's register(address 0x04) to get the IC's version info, I expect to get 0x10 (first version of the IC), but I've got 0xFF instead.

Am I wrong? Or "0xFF" is correct for now?

```
	int32_t value;
	uint8_t readVal;
	txTest(0x32);
	TMC6200_SPIChannel = &HAL.SPI->ch2;
	TMC6200_SPIChannel->CSN = &HAL.IOs->pins->SPI2_CSN1;
	while(1)
	{
		TMC6200_readRegister(0, 0x04, &value);
		readVal = (value >> 24) & 0xFF;
		wait(1000);
		txTest(readVal);
	}
```

**Comment by huskier** [comment]
YES, I do. I connect SPI2_CSN1(PIN25) on L-Board to CS_DRIVER(PIN24) on TMC6200-EVAL board.
Actually, I do not use TMC6200_init() function at all, and instead, I just use two statement for init:
```
	TMC6200_SPIChannel = &HAL.SPI->ch2;
	TMC6200_SPIChannel->CSN = &HAL.IOs->pins->SPI2_CSN1;
```

But if I read 0x00 address, I get the value of "0xE8" for the low 8 bit, and I think it is reasonable.

Could I read the registers from the TMCL-IDE directly? I cannot see the option and interface.

**Comment by trinamic-LH** [comment]
The Value 0xE8 in Register 0x00 implies that bit 7 (test bit) is set, which shouldnt be on by default.

For reading the registers from the IDE there are the register browser and the datagram mode, which allows you to directly send datagrams.
![Register access from the IDE](https://user-images.githubusercontent.com/49403175/56277807-5593ef80-6105-11e9-8c12-686e74e94038.PNG)

**Comment by trinamic-LH** [comment]
Have you tried manually assigning the TMC6200 Driver board?
(click on the "ID1: Landungsbruecke [V 3.06]" tab for the menu)

**Comment by huskier** [comment]
Yes, I do. This TMC6200-EVAL is borrowed from your company, and I just test it today.
I am not sure it is absolutly OK.

![BoardAssignment](https://user-images.githubusercontent.com/5828575/56280509-efc35a00-613c-11e9-899b-7c0f457fa37b.png)

**Comment by trinamic-LH** [comment]
Im running IDE V3.0.22.0 (no relevance to the success of board detection)
Firmware v3.06

Your board might not have the ID value properly programmed into the EEPROM. When running the normal firmware you can manually verify this with the following command in direct mode:
Instruction 65 (0x41) - User Function 1, calls readIdEeprom
Type 2 - use Channel 2, used for drivers
Motor 0 - not relevant
Value 16 (0x10) - the address of the ID in the EEPROM

The reply should have 0x00A0 in the lower 2 Bytes.

![Direct ID Readout](https://user-images.githubusercontent.com/49403175/56281837-eec70400-610d-11e9-8560-048fa13a3160.PNG)

**Comment by huskier** [comment]
What I get is as following. But I still can not see the TMC6200 in the left side tree.

![DirectModeGetEEPROMInfo](https://user-images.githubusercontent.com/5828575/56297608-36c44600-6163-11e9-8782-f95e6bdfb29e.png)

**Comment by trinamic-LH** [comment]
After trying out different IDE versions it appears that the public release of the TMCL-IDE (v3.0.23) does not yet include the TMC6200 in the tree view. I did not consider this option, as the internal build i have installed right now is on Version 3.0.22 and i assumed that your higher Version number would have this driver included.

The next release Version (3.0.24) is currently in the testing phase and has the TMC6200 driver included.
For temporary testing purposes you can use [the nightly version](https://github.com/trinamic/TMCL-IDE-Nightly), which has the driver included aswell.

**Comment by huskier** [comment]
Yes, the version TMC-IDE-3.0.23.0007 does include the TMC6200 in the tree view.
![TMC4671 TMC6200](https://user-images.githubusercontent.com/5828575/56299859-71c87880-6167-11e9-9592-5e9d21453ef1.png)

Next task, I want to let the TMC6200 work in the open loop mode. I tried several time, no success right now. Maybe I need to check lost of information to get is work.

**Comment by huskier** [comment]
The following code is still get "0xFF" instead of expected "0x10".  The TMCL-IDE(3.0.23.007) could get the expected "0x10". Very weird!

```
	// Start all initialization routines
	init();
	int32_t value;
	uint8_t readVal;
	txTest(0x32);
	TMC6200_SPIChannel = &HAL.SPI->ch2;
	TMC6200_SPIChannel->CSN = &HAL.IOs->pins->SPI2_CSN0;
	wait(1000);
	while(1)
	{
		TMC6200_readRegister(0, 0x04, &value);
		readVal = (value >> 24) & 0xFF;
		wait(1000);
		txTest(readVal);
	}
```

**Comment by trinamic-LH** [comment]
Any setup changes other than swapping Firmware?

Could you maybe try verifying the SPI request via an oscilloscope?

**Comment by huskier** [comment]
No setup change, just change from the IDE operation to coding operation.

I will verify the SPI request via an oscilloscope later.

Any way, Thanks!

**Comment by huskier** [comment]
Hi, could you please help test my mini-code under your setup (L-Board + TMCL4671-EVAL + TMC6200-EVAL)?

The IDE could get the right answer for the registers (I tested the VERSION info), but the mini-code can not.

```
	// Start all initialization routines
	init();
	int32_t value;
	uint8_t readVal;
	txTest(0x32);
	TMC6200_SPIChannel = &HAL.SPI->ch2;
	TMC6200_SPIChannel->CSN = &HAL.IOs->pins->SPI2_CSN0;
	wait(1000);
	while(1)
	{
		TMC6200_readRegister(0, 0x04, &value);
		readVal = (value >> 24) & 0xFF;
		wait(1000);
		txTest(readVal);
	}
```

**Comment by trinamic-LH** [comment]
If the IDE + EvalSystem firmware is reading out the correct answers the hardware is working correctly.

The code you posted is incomplete, so testing it is not possible.

**Comment by huskier** [comment]
Hi, the full code is here:
[](https://github.com/huskier/TMC6200SPICommTest
)
Thanks.

**Comment by trinamic-LH** [comment]
Your code does not initialize the variable `TMC6200_SPIChannel` in TMC6200_eval.c
Your function `TMC6200_readRegister()` calls `tmc6200_readInt()`, which calls `tmc6200_readwriteByte()` which in return does an indirect call: `return TMC6200_SPIChannel->readWrite(data, lastTransfer);`

This indirect call requires the `TMC6200_SPIChannel` variable to be initialized. To fix this in your code, you can simply change 
```
static SPIChannelTypeDef *TMC6200_SPIChannel;
```
in your main.c, line 18 to
```
extern SPIChannelTypeDef *TMC6200_SPIChannel;
```
in order to correctly initialize the variable in TMC6200_eval.c

With this change i get the expected Version number (0x10) as a response.

**Comment by huskier** [comment]
OK, I see.

Thank you very much for helping and the commit code.
