### ISSUE TITLE
Does the Landungsbrücke board have a pre-programmed Kinetis ARM chip (MK20DX256VLL10) soldered to the board?

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#14]
To programm the Landungsbruecke board, the bootloader should be downloaded into the chip through SWD (SW_PROG_SWDIO and SW_PROG_SWCLK in the schematic), then the application code could be downloaded through the USB port with Trinamic's TMCL IDE. 

We've designed our customized board with MK20DX256VMC10 according to Landungsbruecke's schematic, but we encounter issues when we try to imitate the programming way of the Landungsbruecke board does.

We've put the issue on  [NXP's community forum,](https://community.nxp.com/thread/539933) and Myke guess that the Landungsbrücke has a pre-programmed Kinetis soldered to board. Is that true? If it is true, how do you pre-programm the ARM chip before soldering to the board?

**Comment by trinamic-ed** [comment]
Hello,

the Landungsbrücke has **no** pre-programmed Kinetis CPU. It is a standard MK20DN512VLL10 cpu on the Landungsbrücke, as labeled on the CPU of the board. We use SEGGER J-Flash to program the CPU. The programming pads are on the bottom of the module and our Bootloader is programmed in the test after module manufacture. 

From our side it would make no sense to put the firmware open source and need an pre-programmed CPU to use it  :-) 

Best regards,
    Enrico

**Comment by huskier** [comment]
Thanks for your information. We may find the problem. Maybe we make the wrong footprint of MK20DX256VMC10. It is a mirror of the correct footprint. What a careless for the footprint!

**Comment by huskier** [comment]
Hi Enrico, 

J-Flash is a PC software. To program the Landungsbrücke board, what kind of hardware do you use? Which pins do you connect to the MK20DX256***? Do you have any fixtures or tools for the chip initial programming? Could you please explain it in more details?

We're talking about the Landungsbrücke board on [the NXP's forum](https://community.nxp.com/thread/539933).

Thanks.
Youbao

**Comment by Lionheart1810** [comment]
Hi,
1. We use the [SEGGER J-Link device](https://www.segger.com/products/debug-probes/j-link/) for programming together with a compatible programming or debugging suite (e.g. [J-Flash](https://www.segger.com/products/debug-probes/j-link/tools/j-flash/about-j-flash/), [Ozone](https://www.segger.com/products/development-tools/ozone-j-link-debugger/)). But basically every SWD interface can be used, you dont have to copy this.
2. The pinout for the bottom pins is as follows (looking from bottom site with Trinamic Logo correctly turned, left to right): upper: SWDIO, SWCLK, lower: GND, VDD.
3. For programming, you can power the board via USB or your debugging interface, if it supports it. This fully depends on your interface. The J-Link does that.

For your own design I advice you to lead out the debugging pins seperately with standard connectors while prototyping and developing, and remove them later. This way, you dont have to hassle with the programming pads requiring additional hardware.

**Comment by mykepredko** [comment]
Enrico,

I've been coaching Youbao on this and there's one point he didn't answer that I'm curious about - what about the K20's reset pin?  In the most recent schematics there is the note "Added MCU reset to programming pads on the bottom side" and an off page connector and net label (which don't seem to go anywhere) have been added (on page 2).  

Could you explain this change?  

Thanx,

myke

**Comment by trinamic-ed** [comment]
Hi,

when programming the cpu directly with the programmer. There is one situation that can block the CPU to program it any more. (When you clear the flash and thus the first bytes with some base settings of the CPU and re-power the CPU). Then the Reset-Pin must be also connected to the programmer. 

![image](https://user-images.githubusercontent.com/1303462/90600228-76d38700-e1f6-11ea-8957-ea47acf55681.png)

Best Regards,
      Enrico

**Comment by mykepredko** [comment]
Hi Erinco,

OK, that matches my understanding of how the Kinetis is programmed.  

Now, the screen shot above, doesn't match anything that's on your website (or at least that I can find).  When I look at the 2.0 schematic on your page, I get a schematic with reset set up like the attached screenshot.  
![2020 08 17 - Trinamic's Landungsbruedke V2 0 Reset](https://user-images.githubusercontent.com/1693313/90643070-24e42e80-e201-11ea-8fe5-237d9765061a.jpeg)

How are the programming pins with reset on the back of the board laid out and how do you wire the J-Link to them?

Thanx,

myke

**Comment by trinamic-ed** [comment]
Hi,

just saw on the website that the "old" schematic is in the zip: https://www.trinamic.com/fileadmin/assets/Products/Eval_Drawings/Landungsbruecke_V20_PCB.zip

Attached is the actual version, I used.

Regards,
    Enrico

[Landungsbruecke v20 Schematic.pdf](https://github.com/trinamic/TMC-EvalSystem/files/5096981/Landungsbruecke.v20.Schematic.pdf)

**Comment by mykepredko** [comment]
Cool.  Thank you.  

Could you please explain the pins on the backside of the Landungsbruecke board (the version 2.0 on the web site still only show four pins) and how you recommend that Youbao should connect the J-Link?  

Thanx,

myke

**Comment by huskier** [comment]
@mykepredko @trinamic-ed 

Hi Myke & Enrico,

For the version 1.2, the pads on the back side of Landungsbruecke board are connected to "SWD_IO", "SWD_CLK", "GND", "+3VD", respectively.

![BackSideOfLandungsbruecke](https://user-images.githubusercontent.com/5828575/90706678-465c1d80-e2c8-11ea-8ea8-fa700f6fb90c.jpg)


From my understanding, SWD is enough for MK20DX256VMC10 initial programming?

Thanks.
Youbao

**Comment by mykepredko** [comment]
@huskier,

I"m not sure that's correct as there's a reset pin somewhere.  

I'd still like @trinamic-ed to reply with where is the _reset pin and how to connect the J-Link to the board.

myke

**Comment by trinamic-LH** [comment]
Hello,

this is the pad layout of the Landungsbruecke v2.0:
<img src="https://user-images.githubusercontent.com/49403175/90727243-41489f80-e2c3-11ea-8094-fabf318b9771.png" width="30%">

The Landungsbruecke v1.2 does not have the reset pad, all others are identical.

Regards,
Lenard

**Comment by huskier** [comment]
@trinamic-LH 

Then, Lenard, how is the RESET pin to connect the J-Link to the board?
In general, do we need the RESET pin for the initial programming?

Regards,
Youbao

**Comment by trinamic-LH** [comment]
@huskier 

As @trinamic-ed mentioned earlier, the reset pin is only required if previous programming locked the CPU. This can occur when changing the security settings of the CPU or when the internal storage is left blank and a power cycle occurs.

The RESET pin should be connected to the nRESET pin of the J-Link controller ( refer to SEGGERs [Interface Description](https://www.segger.com/products/debug-probes/j-link/technology/interface-description/) )

Regards,
Lenard

**Comment by huskier** [comment]
@trinamic-ed @trinamic-LH 

Hi Lenard & Enrico, have you encountered that the 16MHz crystal do not oscillate sometimes? And how do you deal with it?

For our customized board, we can download the bootloader program through SWD, but the crystal does not oscillate at all, so the downloaded program does not run.

Thanks.

Youbao

**Comment by trinamic-LH** [comment]
Hello,

i have checked with @trinamic-ed - we have not encountered any issues with the oscillator on the Landungsbruecke.

Therefore we are unfortunately unable to help you diagnose this issue with your custom design.

Regards,
Lenard
