### ISSUE TITLE
Error for compiling

### ISSUE THREAD

**Issue by xieyiteng** [trinamic/TMC-EvalSystem#15]
If you have time, please help me find a question.Thanks.
My development environment is STM32CubeIDE.
If i need to use eclipse.

16:27:08 **** Build of configuration Release for project TMC-EvalSystem ****
cs-make -s -j8 all 
"-------- begin (mode: ROM_RUN) --------"
process_begin: CreateProcess(NULL, arm-none-eabi-gcc --version, ...) failed.
cs-make: *** No rule to make target `boards/SelfTest_.c', needed by `_build_/SelfTest_.o'.  Stop.
cs-make: *** Waiting for unfinished jobs....
make (e=2): The system could not find the specified file。

cs-make: *** [gccversion] Error 2
"cs-make -s -j8 all" terminated with exit code 2. Build might be incomplete.

16:27:11 Build Failed. 3 errors, 0 warnings. (took 2s.415ms)

**Comment by trinamic-LH** [comment]
Hello,

you need to define which device to build - either `Landungsbruecke` or `Startrampe`.

When calling make directly, add `DEVICE=Landungsbruecke` when building for the Landungsbruecke or `DEVICE=Startrampe` when building for the Startrampe.
If you can find where to add commandline parameters to the make call in the STM32CubeIDE, add it there. If you cannot find it, you can add `DEVICE=Landungsbruecke` (or `DEVICE=Startrampe`) at the top of the Makefile instead.

**Comment by trinamic-LH** [comment]
Commit bdecc24fe07c6d841cadfaaf2a5830f28136cc54 adds an error message if no device has been specified.

**Comment by xieyiteng** [comment]
@trinamic-LH

**Comment by xieyiteng** [comment]
@trinamic-LH trinamic-LH
I have no idea what happend, but, it is solved.
I just did the following::::::::
1、Installed the “Eclipse Embedded CDT” plug-in.
2、Installed "eclipse-inst-jre-win64.exe"
3、Installed “gnu-mcu-eclipse-build-tools-2.9-20170629-1013-win32-setup.exe”
That is funny,haha.I made it.Thanks a million.

>

**Comment by trinamic-LH** [comment]
Are you using one of the Evalsystem build targets? (see picture) These build targets add the necessary parameters to the make call. If you did not change anything but the three above things, it might have been an issue with Eclipse not supplying those parameters to make correctly.

Glad to hear it works now :+1:

Regards,
Lenard

![Evalsystem Build target](https://user-images.githubusercontent.com/49403175/94654618-9aade080-02fd-11eb-80d7-7bc39433156e.PNG)
