### ISSUE TITLE
Is there documentation available?

### ISSUE THREAD

**Issue by qiuwenhui** [trinamic/TMC-EvalSystem#17]
Is there documentation available?I don't know how to use TMC2209 API on my motherboard without documentation!https://github.com/trinamic/TMC-API/tree/0495326ec3d9c054b310a61f971541807a084586

**Comment by Chris-Idema-WizzDev** [comment]
I'm interested in documentation as well. They should at least provide build instructions.

**Comment by trinamic-ed** [comment]
Hi,

please have a look to this App Note: https://www.trinamic.com/fileadmin/assets/Support/AppNotes/AN038_Using_TRINAMICs_IC_Software_API_and_Examples.pdf (located here: https://www.trinamic.com/support/app-notes/)

Regards,
    Enrico

**Comment by trinamic-ed** [comment]
I added the link to the eval system home page and the app note to the main .md file.
