### ISSUE TITLE
When I use a j-link to download BootLoader, the error is displayed：ERROR: Program (0x1FFF0001 - 0x1FFF0003) does not fit into selected flash sectors.

### ISSUE THREAD

**Issue by chenzc217** [trinamic/TMC-EvalSystem#19]
i'm engineer in china.
I used your open source materials to make a Landungsbrücke board 
When I want to download Bootloader V1.00 to MK20DX256VLL10, jflash shows an error: ERROR: Program (0x1FFF0001 - 0x1FFF0003) does not fit into selected flash sectors.
So how should I set up to download this BootLoader to the chip?

Regards,
chenzhichao

**Comment by trinamic-LH** [comment]
Hello,

the MK20DX256VLL10 has a different RAM memory mapping than the MK20DN512VLL10. As a result the bootloader image for the Landungsbruecke is not compatible. Refer to [this issue](https://github.com/trinamic/TMC-EvalSystem/issues/18#issuecomment-805693128) for further details.

Regards,
Lenard

**Comment by chenzc217** [comment]
Hello,
Thank you for your reply. The mcu I used is MK20DN512VLL10, because MK20DN512VLL10&nbsp;is the model in your open source schematic. But this error still appears. BootLoader was downloaded from your company's official website(https://www.trinamic.com/support/eval-kits/details/landungsbruecke/). The J-FLASH version I used is 4.90. and I downloaded the latest version 7.20, but both versions of the software report the same error. I read it on their forums(https://forum.segger.com/index.php/Thread/1817-JFlashARM-flashing-Freescale-Kinetis-data-flash-region/?postID=5704&amp;page=Thread). I found a similar problem, but it seems that SEGGER did not give a solution. I can see the last few data in the opened hex file. I guess it is to verify the integrity of the program, but I noticed that the last few bytes of the hex file are already in the SRAM area of the chip, not the FLASH area, so did you have this problem when you downloaded the BootLoader?
Looking forward to your reply and&nbsp;Thank you very much for your reply again.


Regards,
chenzhichao








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "trinamic/TMC-EvalSystem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 下午2:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [trinamic/TMC-EvalSystem] When I use a j-link to download BootLoader, the error is displayed：ERROR: Program (0x1FFF0001 - 0x1FFF0003) does not fit into selected flash sectors. (#19)





 
Hello,
 
the MK20DX256VLL10 has a different RAM memory mapping than the MK20DN512VLL10. As a result the bootloader image for the Landungsbruecke is not compatible. Refer to this issue for further details.
 
Regards,
 Lenard

**Comment by trinamic-LH** [comment]
Hello chenzhichao,

it appears that the RAM section was left in that bootloader hex file by accident.
There are two possible workarounds to this:

You can fix the file in J-Flash. Go into Edit->Delete Range, then enter the start address 0x1FFF0000 and the end address 0x1FFF0004 to delete the RAM section.

You can alternatively manually remove the section from the hex file by removing these two lines near the end of the file:
```
:020000041FFFDC
:0400000000000000FC
```

I will get the hex file on the website updated, but this will take a few days to run through the internal processes.

Regards,
Lenard
