### ISSUE TITLE
Target Reached

### ISSUE THREAD

**Issue by arazavi19** [trinamic/TMC-EvalSystem#20]
Hello,
When operating Landungsbrücke/TMC4361-EVAL/TMC2660-EVAL in closed loop, I see different behaviors between the followings:

Option 1. 
To check Motion Complete” send (write) the following DATAGRAM to Landungsbrücke:
'01 06 08 00 00 00 00 00 0F'
Then in response check the status of bit 0.

Option 2.
“To check Motion Complete” send (write) the following DATAGRAM to Landungsbrücke:
'01 94 0E 00 00 00 00 00 A3'
Then in response check the status of bit0.

I know Option 2 is reading EVENTS STATUS register of TMC4361A.
I do not know what Option 1 does.
I guess it is calling a routine on Landungsbrücke firmware.

Can you tell me what '01 06 08 00 00 00 00 00 0F' does so I can duplicate it in my Matlab code?

Thanks.

**Comment by trinamic-LH** [comment]
Hello,

the Option 1 reads one of the axis parameters - located [here](https://github.com/trinamic/TMC-EvalSystem/blob/17d7363705187467ac27d323732d79b5d5fbd0e7/boards/TMC4361A_eval.c#L246).
The axis parameter simply does the same as your Option 2.

Regards,
Lenard

**Comment by arazavi19** [comment]
Hello Lenard,
Thanks.
I now understood line 249 of "TMC4361A_eval.c" is checking status of "bit 0" of "TMC4361A_STATUS" register:
      *value = (tmc4361A_readInt(motorToIC(motor), TMC4361A_STATUS) & (1<<0))? 1:0;

Q2. Which of the followings is "TMC4361A_STATUS":
     a. Status Event Register (0x0E)
     b. Status Flag Register (0x0F)
Reason for question:
"TMC-EvalSystem-3.08.7.zip" is downloaded from GitHub.
However, the following folder:
....    TMC-EvalSystem-3.08.7.zip\TMC-EvalSystem-3.08.7\tmc
        is missing "ic" folder which is mentioned in line 3 of "TMC4361A_eval.c":
         #include "tmc/ic/TMC4361A/TMC4361A.h"

Best regards,
Ali

**Comment by trinamic-LH** [comment]
Hello Ali,

the github zip source code [does not contain the source code](https://github.com/dear-github/dear-github/issues/214) of the [submodule TMC-API](https://github.com/trinamic/TMC-API/tree/0495326ec3d9c054b310a61f971541807a084586).
The submodule contents should be in the `TMC-API` folder. Then you have the missing file located at `TMC-API/tmc/ic/TMC4361A/TMC4361A.h`

Regards,
Lenard

**Comment by arazavi19** [comment]
Hello Lenard,
Thanks.
Looking at "TMC4361A.h" and "TMC4361A_eval.c"  indicate that "01 06 08 00 00 00 00 00 0F" will read bit0 status of Register 0x0F (Status Flag Register).

In my code, I read bit0 status of Register 0x0E (Status Event Register).
Before writing to XTARGET, I read 0x0E to clear flags. 
Then I write to XTARGET.
I keep checking bit0 status of 0x0E to determine when it becomes 1.
It works when operating open loop.
In closed loop it has odd behavior and intermittently does not indicate end of motion correct (XACTUAL ~=XTARGET).

I am wondering if there are specific reason your firmware use bit0 of 0x0F instead of 0x0E to detect end of motion.
Do you recommend using 0x0F register instead of 0x0E to detect end of motion?
Looking at datasheet, it seems I must be using 0x0E ...

Thanks.

**Comment by trinamic-LH** [comment]
Hello Ali,

from what i can tell you should use 0x0E during closed loop since the noise of the feedback system can result in the actual position slightly varying instead of staying exactly on target. During that case, the status flag register 0x0F would turn on and off repeatedly while the status event register 0x0E would remember reaching the target position even when the actual position then slightly varies.

I will doublecheck with the IC designer whether i am missing something here.

Regards,
Lenard

**Comment by trinamic-LH** [comment]
Followup from the IC developer:
For the closed loop regulation modes, there is an additional register - ENC_POS_DEV - that modifies the behaviour of the TARGET_REACHED flag and event bits. Refer to section 16.1.1 in the TMC4361A datasheet for details.

Regards,
Lenard
