### ISSUE TITLE
[In tmc4671_eval.c] why is the parameter of moveBy(uint8_t motor, int32_t *ticks)  different from moveTo(uint8_t motor, int32_t position)?

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#22]
Hi, we do not understand why the parameter of moveBy(uint8_t motor, int32_t *ticks)  is different from moveTo(uint8_t motor, int32_t position)? 

Thanks.

**Comment by trinamic-ed** [comment]
Hi,

yes when looking to the TMC4671 implementation, it makes not much sense to use a pointer in moveBy().

But for example for the TMC5130-EVAL, the pointer is used to return the new target position (actual position inside IC + ticks). 

![image](https://user-images.githubusercontent.com/1303462/158761995-4e70a326-6553-4fd0-ac99-bf017e02250a.png)

This saves a little bit communication if you are periodically writing new target positions and read the actual position over the USB connection.

Regards,
    Enrico

**Comment by huskier** [comment]
Thanks for your explanation.

Regards,
Youbao
