### ISSUE TITLE
About reliable initialization of encoder (ABN, without HALL)

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#25]
Is there equivalent code for reliable initialization of encoder (ABN, without HALL) as the Python code (Python_encoder_minimal_movement)?

**Comment by trinamic** [comment]
No, we do not have this kind of initialization in the TMC-API. If you have load on the motor (like in a robotic application) the encoder-init method based on Hall-sensor signals is the better choice.

**Comment by huskier** [comment]
Thanks for reply.
