### ISSUE TITLE
When I connect the Landungsbrücke it's solid red and blinking green

### ISSUE THREAD

**Issue by thalesfsp** [trinamic/TMC-EvalSystem#27]
What does that means? I found something related in this document -> https://www.trinamic.com/fileadmin/assets/Products/Eval_Documents/TMC5130-EVAL_user_manual_hw1.5_rev1.01.pdf

**Comment by trinamic-ed** [comment]
Hi,

I guess you have a setup with Landungsbrücke and TMC5130-EVAL. Is the supply voltage attached to the TMC5130-EVAL? Have you connected the Landungsbrücke via USB? For more details of the error, please have a look to the TMCL-IDE: https://www.trinamic.com/fileadmin/assets/Support/Software/TMCL-IDE/TMCL-IDE-3.5.0.0-Setup.exe 

Regards,
     Enrico

**Comment by thalesfsp** [comment]
Thank you @trinamic-ed! Why there's no support for Mac OS?

**Comment by trinamic-ed** [comment]
Hi,

on this page a version for Linux is available. Does this help?

Regards,
     Enrico

**Comment by thalesfsp** [comment]
Hi, Enrico. This is for Linux, I use Mac OS, from Apple. They are not the same.

**Comment by trinamic-ed** [comment]
Hi,

yes, this is clear. In the moment we provide Windows and Linux version only. We will check, if we can provide a Mac OS version in the future.

Regards,
     Enrico

**Comment by thalesfsp** [comment]
Thank you for closing the issue..
