### ISSUE TITLE
Two questions about tmc4671_doEncoderInitializationMode2(...)

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#28]
In the following function of tmc4671_doEncoderInitializationMode2, there is a code snippet which select the use of phi_e_hall to start motor with hall signals. 
```
		// normally MOTION_MODE_UQ_UD_EXT is only used by e.g. a wizard, not in normal operation
		if (TMC4671_FIELD_READ(motor, TMC4671_MODE_RAMP_MODE_MOTION, TMC4671_MODE_MOTION_MASK, TMC4671_MODE_MOTION_SHIFT) != TMC4671_MOTION_MODE_UQ_UD_EXT)
		{
			// select the use of phi_e_hall to start motor with hall signals
			tmc4671_writeRegister16BitValue(motor, TMC4671_PHI_E_SELECTION, BIT_0_TO_15, TMC4671_PHI_E_HALL);
		}
```
For this code snippet, we have two questions:
1. After selecting the  use of phi_e_hall to start motor with hall signals, where do we explicitly make the motor moving? OR the motor move automatically after selecting the use of phi_e_hall? We do not understand how or why the motor is moving after select phi_e_hall?
2. If MOTION_MODE_UQ_UD_EXT is the current mode, i.e. 
TMC4671_FIELD_READ(motor, TMC4671_MODE_RAMP_MODE_MOTION, TMC4671_MODE_MOTION_MASK, TMC4671_MODE_MOTION_SHIFT) = TMC4671_MOTION_MODE_UQ_UD_EXT
then, what happens for the function of tmc4671_doEncoderInitializationMode2(...)?

Thanks.

```
void tmc4671_doEncoderInitializationMode2(uint8_t motor, uint8_t *initState, uint16_t *actualInitWaitTime,
		int16_t *hall_phi_e_old, int16_t *hall_phi_e_new, int16_t *hall_actual_coarse_offset, uint16_t *last_Phi_E_Selection)
{

	static int16_t SumTimeTemp = 0; //在位时判断时间
	switch (*initState)
	{
	case STATE_NOTHING_TO_DO:
		*actualInitWaitTime = 0;
		break;
	case STATE_START_INIT: // started by writing 1 to initState

		//dispString("[Mode2] In case STATE_START_INIT:... ");

		// save actual set value for PHI_E_SELECTION
		*last_Phi_E_Selection = (uint16_t)tmc4671_readRegister16BitValue(motor, TMC4671_PHI_E_SELECTION, BIT_0_TO_15);

		// turn hall_mode interpolation off (read, clear bit 8, write back)
		tmc4671_writeInt(motor, TMC4671_HALL_MODE, tmc4671_readInt(motor, TMC4671_HALL_MODE) & 0xFFFFFEFF);

		// set ABN_DECODER_PHI_E_OFFSET to zero
		tmc4671_writeRegister16BitValue(motor, TMC4671_ABN_DECODER_PHI_E_PHI_M_OFFSET, BIT_16_TO_31, 0);

		// read actual hall angle
		*hall_phi_e_old = TMC4671_FIELD_READ(motor, TMC4671_HALL_PHI_E_INTERPOLATED_PHI_E, TMC4671_HALL_PHI_E_MASK, TMC4671_HALL_PHI_E_SHIFT);

		// read actual abn_decoder angle and compute difference to actual hall angle
		*hall_actual_coarse_offset = tmc4671_getS16CircleDifference(*hall_phi_e_old, (int16_t) tmc4671_readRegister16BitValue(motor, TMC4671_ABN_DECODER_PHI_E_PHI_M, BIT_16_TO_31));

		// set ABN_DECODER_PHI_E_OFFSET to actual hall-abn-difference, to use the actual hall angle for coarse initialization
		tmc4671_writeRegister16BitValue(motor, TMC4671_ABN_DECODER_PHI_E_PHI_M_OFFSET, BIT_16_TO_31, *hall_actual_coarse_offset);

		// normally MOTION_MODE_UQ_UD_EXT is only used by e.g. a wizard, not in normal operation
		if (TMC4671_FIELD_READ(motor, TMC4671_MODE_RAMP_MODE_MOTION, TMC4671_MODE_MOTION_MASK, TMC4671_MODE_MOTION_SHIFT) != TMC4671_MOTION_MODE_UQ_UD_EXT)
		{
			// select the use of phi_e_hall to start motor with hall signals
			tmc4671_writeRegister16BitValue(motor, TMC4671_PHI_E_SELECTION, BIT_0_TO_15, TMC4671_PHI_E_HALL);
		}

		*initState = STATE_WAIT_INIT_TIME;
		break;
	case STATE_WAIT_INIT_TIME:
		// read actual hall angle
		*hall_phi_e_new = TMC4671_FIELD_READ(motor, TMC4671_HALL_PHI_E_INTERPOLATED_PHI_E, TMC4671_HALL_PHI_E_MASK, TMC4671_HALL_PHI_E_SHIFT);

		// wait until hall angle changed
		if(*hall_phi_e_old != *hall_phi_e_new)
		{
			// estimated value = old value + diff between old and new (handle int16_t overrun)
			int16_t hall_phi_e_estimated = *hall_phi_e_old + tmc4671_getS16CircleDifference(*hall_phi_e_new, *hall_phi_e_old)/2;

			// read actual abn_decoder angle and consider last set abn_decoder_offset
			int16_t abn_phi_e_actual = (int16_t) tmc4671_readRegister16BitValue(motor, TMC4671_ABN_DECODER_PHI_E_PHI_M, BIT_16_TO_31) - *hall_actual_coarse_offset;

			// set ABN_DECODER_PHI_E_OFFSET to actual estimated angle - abn_phi_e_actual difference
			tmc4671_writeRegister16BitValue(motor, TMC4671_ABN_DECODER_PHI_E_PHI_M_OFFSET, BIT_16_TO_31, tmc4671_getS16CircleDifference(hall_phi_e_estimated, abn_phi_e_actual));

			// switch back to last used PHI_E_SELECTION setting
			tmc4671_writeRegister16BitValue(motor, TMC4671_PHI_E_SELECTION, BIT_0_TO_15, *last_Phi_E_Selection);

			// go to ready state
			*initState = 0;

			//dispString("[Mode2] In if(hall_phi_e_old != hall_phi_e_new)......");
		}
		else
		{
			// go to ready state
			SumTimeTemp += 1;
			if(SumTimeTemp == 10000)
			{
				*initState = 0;
				SumTimeTemp = 0;
				//dispString("[Mode2] In if(hall_phi_e_old == hall_phi_e_new).......");
			}

		}
		break;
	default:
		*initState = 0;
		break;
	}
}
```

**Comment by trinamic-ed** [comment]
Hi,

MOTION_MODE_UQ_UD_EXT is only used if you want to turn the motor in a voltage driven mode with an electrical angle controlled by the open loop generator of the TMC4671 and a defined voltage duty cycle. This is typically needed, to check if the motor phase currents match the phase voltages (e.g. in the Wizard in the TMCL-IDE). If this is configured correct, then the torque mode should be used to control the motor current/flux.

If you want to align the encoder with encoder init method 2, the torque mode (or based on that e.g. the velocity mode) should be used to control the current/flux in the motor. The hall sensor signals are used to have a rough commutation angle PHI_E, to create force from the given current/flux to turn the motor until the next hall sensor change happens and the encoder counter can be updated with the more accurate information than the 60° resolution of the hall sensor signals.

Regards,
     Enrico

**Comment by huskier** [comment]
Thanks for your reply. 

For the torque mode in encoder init method 2, how much does the torque applied for the system? The default one? For our system, sometimes the encoder init(method 2) could be successful, but sometimes the encoder init failed. We guess there are no enough force to make the system move.

**Comment by huskier** [comment]
Thanks for your reply. 

For the torque mode in encoder init method 2, how much does the torque applied for the system? The default one? For our system, sometimes the encoder init(method 2) could be successful, but sometimes the encoder init failed. We guess there are no enough force to make the system move.

**Comment by trinamic-ed** [comment]
Hi, 

depends from your system/application. You can e.g. use velocity mode and command a target velocity and let the velocity controller command the needed torque to the torque controller.

Regards,
     Enrico

**Comment by Ayoub-pixe** [comment]
Hi @huskier, 
I came across this GitHub issue and I was wondering if you have found a solution to the problem you mentioned earlier? I ask because I recently encountered a similar issue in one of my projects and unfortunately, I ended up with some motor damage due to initialization failure (the current goes very high at the beginning) .
It would be great if you could provide an update on your progress with this issue. Any insights or solutions you have found would be greatly appreciated. Thank you !!
