### ISSUE TITLE
【Suggest】It is good to make the printf(...) function workable.

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#4]
Hi. When people use the TMC-EvalSystem to test their  idea, a workable printf(...)  function would be very helpful, although there are already tx(...) and txN(...) functions there.  Could you please consider implementing the printf(...) function?

**Comment by Lionheart1810** [comment]
While printf is not provided, sprintf is by default. One could simply print stuff to a buffer string and send it over UART via txN.
Problem with printf is that we need to define a default output channel for that, which is impossible due to possibilities in combinations of channels.

**Comment by huskier** [comment]
I've gotten it. Thanks.
