### ISSUE TITLE
【Possible issue】 the init(...) function in the main.c

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#5]
In the init() function of the main.c, line 78-80:
```
	// We disable the drivers before configurating anything
	HAL.IOs->config->toOutput(&HAL.IOs->pins->DIO0);
	HAL.IOs->config->setHigh(&HAL.IOs->pins->DIO0);
```
The comment said disable the driver, but the action is to set the DIO0 high. Is this a problem?

**Comment by Lionheart1810** [comment]
No, driver enable pins are negated by default, so high means disabled.
