### ISSUE TITLE
Possible problems in the TMC4671_init(...) function in the TMC4671_eval.c file

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#6]
In the TMC4671_init(...), there is code through line 1473 to 1476
```
	// configure ENABLE-PIN for TMC4671
	PIN_DRV_ENN = &HAL.IOs->pins->DIO0;
	HAL.IOs->config->toOutput(PIN_DRV_ENN);
	HAL.IOs->config->setHigh(PIN_DRV_ENN);
```
and also the code in line 1542
`	enableDriver(DRIVER_ENABLE);`

I think these two place are duplicate in function.

**Comment by Lionheart1810** [comment]
3101abe58b5844a7b8b7dc8c64677e727efd357f
