### ISSUE TITLE
Comment is not consistent with the real Landungsbruecke board's schematic

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#8]
In hal/Landungsbruecke/tmc/SPI.c, line 92, the comment is not consistent with the real Landungsbruecke board's schematic.
// configure SPI2 pins PORTB_PCR21(SCK), PORTB_PCR23(SDI), PORTB_PCR22(SDO), PORTC_PCR0(CSN0), PORTA_PCR0(CSN5), PORTA_PCR4(CSN2)

For the CSN1 and CSN2, I think they should be PORTA_PCR5 and PORTC_PCR4.

Also, in hal/Landungsbruecke/tmc/IOMap.c, line 300, I do not understand the comment.
.SPI2_CSN1 =  // IOPinTypeDef SPI2_CSN1 Konflikt mit DIO5
Does it mean SPI2_CSN1 conflict with DIO5?

**Comment by trinamic-LH** [comment]
tl;dr: Both of these instances are leftovers from older versions and are outdated.

The first comment appears to be leftover from an old version that did not use the generic HAL implementation yet. With the current HAL the corresponding PORTx_PCRn Registers are set in hal/Landungsbruecke/tmc/IOs.c (Line 45-103):
```
static void setPinConfiguration(IOPinTypeDef *pin)
{
	/* snip */
	PORT_PCR_REG(pin->portBase, pin->bit) = config;
}
```
The pin mapping is - just like that comment - outdated and will be adjusted.

Regarding the second comment - SPI2_CSN1 is mapped to Port A, Pin 5, DIO5 is mapped to Port B, Pin 3.   There is no conflict between them.
