### ISSUE TITLE
Could we manipulate the EEPROM from the TMCL-IDE?

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#9]
Hi, we've found that you've updated the EEPROM.c dramatically. I wonder could we manipulate the EEPROM from the TMCL-IDE?

Iis The EEPROM  AT25128B?

**Comment by trinamic-LH** [comment]
Hi,

the EEPROM used is an AT25128B, yes.

The EEPROM is currently used to detect which EvalBoard is connected to the µC. Access to the EEPROM from the TMCL-IDE is for now only available in internal versions.

If you want to use it in your own software you can use the read/write functions in tmc/EEPROM.h. To ensure future compatibility do not use the first KB of memory, as we may use that region for future extensions beyond the ID detection mechanisms currently in use.

**Comment by huskier** [comment]
I tried the EEPROM read/write with the following code, but no success. Could you please help us a little bit?

I use SPI2 on Landungsbruecke board (L-Board for simple) to directly connect to the PowerStage Board(TMC-UPS-10A/70V). for the wire things:
L-Board                      TMC-USP-10A/70V
SPI2_SCK (PIN27)       SPI2_SCK                          
SPI2_MOSI (PIN29)    SPI2_MOSI
SPI2_MISO(PIN28)     SPI2_MISO
ID_CH1(PIN7)             ID_CH1
I also connected +5V_VM(PIN42), GND(PIN44), VM(PIN1), GND(PIN3) together.

/* main function */
int main(void)
{
	// Start all initialization routines
	init();
	uint8_t readVal;
	txTest(0x35);         // **my own code, the 0x35 can be seen from the PC......**
	//EEPROM_SPIChannel = &HAL.SPI->ch2;    //static SPIChannelTypeDef *EEPROM_SPIChannel;
	EEPROM_SPIChannel = &SPI.ch2;                // I tried the above line and the current line......
	// Main loop
	while(1)
	{
		eeprom_write_byte(EEPROM_SPIChannel, 1025, 0x38);
		wait(1000);
		readVal = eeprom_read_byte(EEPROM_SPIChannel, 1025);
		wait(1000);
		txTest(readVal);
	}
	return 0;
}

my txTest fuction is in TMCL.c file, and looks like:
void txTest(uint8 ch)
{
	uint8 reply[2];
	reply[0] = ch;
	(&interfaces[1])->txN(reply, 1);
}
